admin/controllers/BaseController.php
<?php
namespace admin\controllers;

use  Yii;
use admin\models\AdminLog;
use common\components\Sms;
use common\components\Uploader;
use common\models\SmsTemplet;

class BaseController extends \yii\web\Controller{
    public function init()
    {
		$this->enableCsrfValidation = false;

		if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
    }

    /**
     * 添加操作记录
     * @param string $record 操作描述
     * @param string $data 操作库名和id
     */
    public function addAdminLog($record, $data)
    {
        $log_model = new AdminLog();
        $log_model->admin_id = Yii::$app->user->identity->id;
        $log_model->client_ip = $this->get_client_ip(0,true);
        $log_model->record = $record;
        $log_model->data = $data;
        $log_model->created_at = date('Y-m-d H:i:s');
        $log_model->save();
    }

	/**
	 * 获取客户端IP地址
	 * @param integer $type 返回类型 0 返回IP地址 1 返回IPV4地址数字
	 * @param boolean $adv 是否进行高级模式获取（有可能被伪装）
	 * @return mixed
	 */
	public function get_client_ip($type = 0,$adv=false) {
		$type       =  $type ? 1 : 0;
		static $ip  =   NULL;
		if ($ip !== NULL) return $ip[$type];
		if($adv){
			if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
				$arr    =   explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
				$pos    =   array_search('unknown',$arr);
				if(false !== $pos) unset($arr[$pos]);
				$ip     =   trim($arr[0]);
			}elseif (isset($_SERVER['HTTP_CLIENT_IP'])) {
				$ip     =   $_SERVER['HTTP_CLIENT_IP'];
			}elseif (isset($_SERVER['REMOTE_ADDR'])) {
				$ip     =   $_SERVER['REMOTE_ADDR'];
			}
		}elseif (isset($_SERVER['REMOTE_ADDR'])) {
			$ip     =   $_SERVER['REMOTE_ADDR'];
		}
		// IP地址合法验证
		$long = sprintf("%u",ip2long($ip));
		$ip   = $long ? array($ip, $long) : array('0.0.0.0', 0);
		return $ip[$type];
	}

	/**
     * json转换
     * @param  $ret =>状态码,$msg=>包含信息,$data=>数据,
     * @return json
     * @author ycl
     * @date 2018/4/17
     */
    public function json($ret, $msg = '', $data = array())
    {
        $dataRet = array('code' => $ret);
        $dataRet['msg'] = $msg;
        $dataRet['data'] = $data;
        $dataJson = json_encode($dataRet, JSON_UNESCAPED_SLASHES);
        echo $dataJson;die();
    }

	//检查操作权限
	public function checkrolepre()
    {
        $controller = Yii::$app->controller->id;
		$action =Yii::$app->controller->action->id;
		CheckpreController::checkpre($controller,$action);
    }

    //发送短信
    public function sendSms($tel, $content){
        //获取Sms对象
        $sms_model = new Sms(Yii::$app->params['jvtdSmsUrl'],Yii::$app->params['jvtdSmsUid'],Yii::$app->params['jvtdSmsPass']);
        //发送短信
        $res = $sms_model->SendSms($tel, $content);
        //记录短信发送
        $txt = '['.date('Y-m-d H:i:s').']'.'手机号：'.$tel.'。内容：'.$content.'【返回结果：code：'.$res['error_code'].'，msg：'.$res['error_msg'].'】';
        $this->writeLog($txt, 'sendsms');
        //返回发送结果
        if($res['error_code'] > 0){
            return true;
        }
        return false;
    }

    /**
     * ueditor编辑器 文件上传
     * @author  lvhengbin
     * @time    2019/06/04
     */
    public function actionUploadfile() {
        $config = array(
            "pathFormat" => '/upload/{yyyy}{mm}{dd}/{time}{rand:6}',    //图片保存路径
            "maxSize" => 10485760,   //上传大小限制，单位B
            "allowFiles" => [".png", ".jpg", ".jpeg", ".gif", ".bmp"]   //上传图片格式限制
        );
        $fieldName = 'upfile';
        $up = new Uploader($fieldName, $config);
        $info = $up->getFileInfo();
        $info['url'] = Yii::$app->params['kffileDomain'] . $info['url'];
        /* 返回数据 */
        return json_encode($info);
    }

    /**
     * 给服务人员发送短信模板套用
     * @author  lvhengbin
     */
    public function serverTem($staff, $date, $address, $server, $remarks)
    {
        $tem_two_data = SmsTemplet::find()->where(['type'=>2])->asArray()->one();
        $cont = $tem_two_data['content'];
        $cont = str_replace('{staff}', $staff, $cont);
        $cont = str_replace('{date}', $date, $cont);
        $cont = str_replace('{address}', $address, $cont);
        $cont = str_replace('{server}', $server, $cont);
        $cont = str_replace('{remarks}', $remarks, $cont);
        return $cont;
    }

    /**
     * 给客户发送短信模板套用
     * @author  lvhengbin
     */
    public function userTem($user, $order, $staff, $date, $staffphone, $serverphone)
    {
        $tem_two_data = SmsTemplet::find()->where(['type'=>3])->asArray()->one();
        $cont = $tem_two_data['content'];
        $cont = str_replace('{user}', $user, $cont);
        $cont = str_replace('{order}', $order, $cont);
        $cont = str_replace('{staff}', $staff, $cont);
        $cont = str_replace('{date}', $date, $cont);
        $cont = str_replace('{staffphone}', $staffphone, $cont);
        $cont = str_replace('{serverphone}', $serverphone, $cont);
        return $cont;
    }

    /**
     * 报事报修 员工 短信模板
     * @author  lvhengbin
     */
    public function repairTem($staff, $address, $problem)
    {
        $tem_data = SmsTemplet::find()->where(['type'=>4])->asArray()->one();
        $cont = $tem_data['content'];
        $cont = str_replace('{staff}', $staff, $cont);
        $cont = str_replace('{address}', $address, $cont);
        $cont = str_replace('{problem}', $problem, $cont);
        return $cont;
    }

    /**
     * 报事报修 联系人 短信模板
     * @author  lvhengbin
     */
    public function repairTem2($staff)
    {
        $tem_data = SmsTemplet::find()->where(['type'=>5])->asArray()->one();
        $cont = $tem_data['content'];
        $cont = str_replace('{staff}', $staff, $cont);
        return $cont;
    }

    /**
     * 创建目录
     * @author  mfh
     * @time    2018/1/22
     */
    public function mk_dir($dir, $mode = 0755)
    {
        if (is_dir($dir) || @mkdir($dir,$mode)) return true;
        if (!$this->mk_dir(dirname($dir),$mode)) return false;
        return @mkdir($dir,$mode);
    }

    //记录日志
    public function writeLog($txt, $filename) {
        $path = '../runtime/logs';
        if(!is_dir($path)){
            mkdir($path,0777,true);
        }
        $filename = date('Ym').'_'.$filename;
        $path = $path .'/'. $filename .'.txt';
        if(!empty($txt)) {
            file_put_contents($path, $txt . PHP_EOL, FILE_APPEND);
        }
    }

    public function alert($message,$url='')
    {
        echo "<!DOCTYPE html>
			   <html>
               <head>
				   <meta charset='UTF-8'>
                   <meta name='viewport' content='width=device-width, height=device-height, initial-scale=1,minimum-scale=1, maximum-scale=1, user-scalable=0'>
				   <link rel='stylesheet' href='/layui/css/layui.css'>
				   <script src='/layui/layui.js'></script>
               </head>
               <script type='text/javascript'>
			        layui.use('layer', function(){
					var $ = layui.jquery, layer = layui.layer;
				    layer.ready(function(){
						layer.alert('".$message."',{
						  title: '提示信息'
						  ,skin: 'layui-layer-molv'
						  ,btnAlign: 'c'
						  ,closeBtn: 0
						  ,anim: 4 //动画类型
						}, function(){
						    var url_len = '".$url."'.length;
						    if (url_len == 0) {
						        history.go(-1);
						    } else {
						       location.href = '".$url."';
						    }

						});
						});
					});
                </script>
               </html>";exit;
    }

	public function alertone($message,$url='')
    {
        echo "<!DOCTYPE html>
			   <html>
               <head>
				   <meta charset='UTF-8'>
                   <meta name='viewport' content='width=device-width, height=device-height, initial-scale=1,minimum-scale=1, maximum-scale=1, user-scalable=0'>
				   <link rel='stylesheet' href='/layui/css/layui.css'>
				   <script src='/layui/layui.js'></script>
               </head>
               <script type='text/javascript'>
			        layui.use('layer', function(){
					var $ = layui.jquery, layer = layui.layer;
				    layer.ready(function(){
						layer.alert('".$message."',{
						  title: '提示信息'
						  ,skin: 'layui-layer-molv'
						  ,btnAlign: 'c'
						  ,closeBtn: 0
						  ,anim: 4 //动画类型
						}, function(){
							layer.close(layer.index);
							var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
							window.parent.location.href='".$url."';
							parent.layer.close(index);
						});
						});
					});
                </script>
               </html>";exit;
    }
}

admin/controllers/SgoodscategoryController.php
<?php

namespace admin\controllers;

use Yii;
use yii\data\Pagination;
use common\models\SGoodsCategory;
// 商品分类
class SgoodscategoryController extends BaseController{

    /**
     * 商品分类列表
     *
     * @return array
     */
    public function actionIndex(){
        $getForm = Yii::$app->request->get();
        $query = SGoodsCategory::find();
        $where['is_del'] = 0;
        $query = $query->where($where);
        if (isset($getForm['name']) && $getForm['name'] != '') {      // 名称
            $query = $query->andFilterWhere(['like', 'name', $getForm['name']]);
        }

        $page = (isset($getForm['page']) && $getForm['page']) ? $getForm['page'] : 1;
        $limit = (isset($getForm['limit']) && $getForm['limit']) ? $getForm['limit'] : 10;

        $allcount = $query->count();
        $pagination = new Pagination([
            'defaultPageSize' => $limit,
            'totalCount' => $allcount
        ]);
        $allData = $query->orderBy('id ASC')->offset($pagination->offset)->limit($pagination->limit)->all();

        return $this->render('index', [
            'datas'=>$allData,
            'getForm' => $getForm,// 筛选条件
            'page' => $page,
            'limit' => $limit,
            'count' => $allcount
        ]);
    }

    /*
     * 添加分类页面
     */
    public function actionAdd(){
        return $this->render('add');
    }

    /**
     * 修改分类页
     *
     * @param int    $id     分类Id
     * @return array
     */
    public function actionEdit(){
        $id = Yii::$app->request->get('id');
        if(empty($id)){
            $this->alert('系统错误，请重试！');exit;
        }
        $data = SGoodsCategory::find()->where(['id' => $id, 'is_del'=> 0])->one();
        if(empty($data)){
            $this->alert('系统错误，请重试！');exit;
        }
        return $this->render('edit',[
            'data' => $data,
            'id' => $id,
        ]);
    }
    /**
     * 保存数据
     *
     * @param int    $id         分类Id
     * @param str    $name       分类名称
     * @param str    $icon_img   分类图标
     * @return string
     */
    public function actionSave(){
        if(Yii::$app->request->post()){
            $form = Yii::$app->request->post();
            if(empty($form['name'])){
                $this->alert('请输入分类名称');exit;
            }
            if(empty($form['icon_img'])){
                $this->alert('请上传分类图标');exit;
            }
            $icon_img = str_replace(Yii::$app->params['fileDomain'], '', $form['icon_img']);

            $record = '';
            if(isset($form['id']) && !empty($form['id'])){
                $_model = SGoodsCategory::find()->where(['id' => $form['id']])->one();
                $record = '商城分类编辑';
            }else{
                $_model = new SGoodsCategory();
                $record = '商城分类添加';
            }
            if($_model->icon_img != $icon_img){
                $_model->icon_img = $icon_img;
            }
            $_model->name = $form['name'];
            if($_model->save()){
                $this->addAdminLog($record,'表:hm_s_goods_category,id:'.$_model->id);
                $this->alert('提交成功', '/sgoodscategory/index');exit;
            }else{
                $this->alert('提交失败，请重试！');exit;
            }
        }
    }
    /*
     * 删除
     *
     * @param int    $id         分类Id
     */
    public function actionDelete(){
        $id = Yii::$app->request->get('id');
        if(empty($id)){
            $this->json('400','系统错误，请重试！');
        }

        $model = SGoodsCategory::find()->where(['id' => $id])->one();
        $model->is_del = 1;
        $model->deleted_at = date('Y-m-d H:i:s');
        $model->save();
        $this->addAdminLog('商城分类删除','表:hm_s_goods_category,id:'.$model->id);

        $this->json('200','操作成功');
    }

}

admin/views/sgoodscategory/add.php
<?php

use yii\helpers\Html;

$this->title = '商城分类管理';
?>
<span class="layui-breadcrumb">
  <a href="/">首页</a>
  <a><cite><?=$this->title?></cite></a>
</span>
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
    <legend>添加分类</legend>
</fieldset>

<form class="layui-form" action="/sgoodscategory/save" method='post'>
    <input type="hidden" value="<?php echo Yii::$app->request->csrfToken; ?>" name="_csrf" >
    <div class="layui-form-item">
        <label class="layui-form-label">分类名称</label>
        <div class="layui-input-inline">
            <input type="text" name="name" required  lay-verify="required" placeholder="请输入名称" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">分类图标</label>
        <div class="layui-inline">
            <div class="layui-upload">
                <button type="button" class="layui-btn" id="levelimg">点击上传</button>
                <div class="layui-upload-list" id="img_show" style="width: 50px;height: 50px">
                </div>
            </div>
            <input type="hidden" id='img_val' name="icon_img" value='' required  lay-verify="required">
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>
</form>

<script>
    //Demo
    layui.use(['form', 'layedit', 'laydate'], function(){
        var form = layui.form
            ,layer = layui.layer
            ,layedit = layui.layedit
            ,laydate = layui.laydate;
        //日期
        laydate.render({
            elem: '#date',
            type: 'date'
        });
    });
    layui.use('upload', function(){
        var $ = layui.jquery
            ,upload = layui.upload;

        //普通图片上传
        var uploadInst = upload.render({
            elem: '#levelimg'
            ,field: 'upfile'
            ,url: '/base/uploadfile'
            ,done: function(res){
                if(res.state == 'SUCCESS'){
                    $("#img_show").html('<img src="'+res.url+'" style="width: 100%;height: 100%;" />');
                    $("#img_val").val(res.url);
                }else{
                    myalert(res.state);
                }
            }
            ,error: function(){
                myalert('上传失败，请刷新页面重试');
            }
        });
    });
</script>

admin/views/sgoodscategory/edit.php
<?php

use yii\helpers\Html;

$this->title = '首页分类管理';
?>
<span class="layui-breadcrumb">
  <a href="/">首页</a>
  <a><cite><?=$this->title?></cite></a>
</span>
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
    <legend>编辑分类</legend>
</fieldset>

<form class="layui-form" action="/sgoodscategory/save" method='post'>
    <input type="hidden" value="<?php echo Yii::$app->request->csrfToken; ?>" name="_csrf" >
    <input type="hidden" name="id" value="<?=$data['id']?>">
    <div class="layui-form-item">
        <label class="layui-form-label">分类名称</label>
        <div class="layui-input-inline">
            <input type="text" name="name" value="<?=$data['name']?>" required  lay-verify="required" placeholder="请输入名称" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">分类图标</label>
        <div class="layui-inline">
            <div class="layui-upload">
                <button type="button" class="layui-btn" id="levelimg">点击上传</button>
                <div class="layui-upload-list" id="img_show" style="width: 50px;height: 50px">
                    <img src="<?=$data['icon_img']?>" style="width: 100%;height: 100%;" />
                </div>
            </div>
            <input type="hidden" id='img_val' name="icon_img" value="<?=$data['icon_img']?>" required  lay-verify="required">
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>
</form>

<script>
    //Demo
    layui.use(['form', 'layedit', 'laydate'], function(){
        var form = layui.form
            ,layer = layui.layer
            ,layedit = layui.layedit
            ,laydate = layui.laydate;
        //日期
        laydate.render({
            elem: '#date',
            type: 'date'
        });
    });
    layui.use('upload', function(){
        var $ = layui.jquery
            ,upload = layui.upload;

        //普通图片上传
        var uploadInst = upload.render({
            elem: '#levelimg'
            ,field: 'upfile'
            ,url: '/base/uploadfile'
            ,done: function(res){
                if(res.state == 'SUCCESS'){
                    $("#img_show").html('<img src="'+res.url+'" style="width: 100%;height: 100%;" />');
                    $("#img_val").val(res.url);
                }else{
                    myalert(res.state);
                }
            }
            ,error: function(){
                myalert('上传失败，请刷新页面重试');
            }
        });
    });
</script>

admin/views/sgoodscategory/index.php
<?php
use yii\helpers\Html;
$this->title = '商城分类管理';
?>
<span class="layui-breadcrumb">
  <a href="/">首页</a>
  <a><cite><?=$this->title?></cite></a>
</span>
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
    <legend'商城分类管理</legend>
</fieldset>

<a href="/sgoodscategory/add" class="layui-btn layui-btn-sm"><i class="layui-icon"></i>新增</a>

<table class="layui-table">
    <thead>
    <tr>
        <th>序号</th>
        <th>分类名称</th>
        <th>分类图标</th>
        <th>上传时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <?php if(isset($datas) && !empty($datas)){ ?>
        <?php foreach($datas as $key=>$value){?>
            <tr>
                <td><?=$value['id']?></td>
                <td><?=$value['name']?></td>
                <td><img src="<?=$value['icon_img']?>" width="50px" height="50px" /></td>
                <td><?=$value['created_at']?></td>
                <td>
                    <a class="layui-btn layui-btn-xs" href="/sgoodscategory/edit?id=<?=$value['id']?>" >编辑</a>
                    <a class="layui-btn layui-btn-danger layui-btn-xs" id="<?=$value['id']?>" onclick="Deleteone(this.id)" >删除</a>
                </td>
            </tr>
        <?php }}else{ ?>
        <tr>
            <td colspan='5' style="text-align: center">暂无数据</td>
        </tr>

    <?php }?>

    </tbody>
</table>
<div id="demo3"></div>

<script>
    layui.use(['form', 'layedit', 'laydate','laypage'], function(){
        var form = layui.form
            ,layer = layui.layer
            ,layedit = layui.layedit
            ,laydate = layui.laydate
            ,laypage = layui.laypage;
        laypage.render({
            elem: 'demo3'
            ,count: <?=$count?>
            ,layout:['count','prev', 'page', 'next','limit','skip']
            ,curr:<?=$page?>
            ,limit:<?=$limit?>
            ,jump: function(obj, first){
                var page=obj.curr; //得到当前页，以便向服务端请求对应页的数据。
                var limit=obj.limit; //得到每页显示的条数
                var js_str = 'page='+page+'&limit='+limit;
                var form_str = $("#search_form").serialize();
                var form_arr = form_str.split('&');
                form_arr.splice(0,1);
                form_str = form_arr.join("&");
                form_str = js_str+'&'+form_str;
                //首次不执行
                if(!first){
                    window.location.href = "/sgoodscategory/index?"+form_str;
                }
            }
        });
        laydate.render({
            elem: '#created_at' //指定元素
        });
        laydate.render({
            elem: '#end_at' //指定元素
        });
    });

    //删除
    function Deleteone(obj){
        layer.confirm('确认删除吗？', function(index){
            $.get('/sgoodscategory/delete',{'id':obj},function (ret) {
                layer.close(index);
                if(ret.code == '200'){
                    reloadalert(ret.msg);
                }else{
                    myalert(ret.msg);
                }
            },'json');
        });
    }
</script>